### ISSUE TITLE
Code snippet not visible for Serenity Screenplay documentation 

### ISSUE THREAD

**Issue by s4ik4t** [serenity-bdd/the-serenity-book#18]
The code snippet mentioned in Serenity Screenplay tutorial is not visible:

https://serenity-bdd.github.io/theserenitybook/latest/serenity-screenplay.html#_screenplay_pattern_tests_runs_like_any_other_serenity_test

In the .adoc file, following error was seen:
`include file not found:`

**Comment by saikat-sen-gupta** [comment]
@wakaleo @jan-molak if you can kindly point me to the relevant source code file, I can raise a PR to fix this. I would like to be a frequent committer for serenity-bdd repositories :)
