### ISSUE TITLE
merge serenity.version and serenity.maven.version in the examples

### ISSUE THREAD

**Issue by globalworming** [serenity-bdd/the-serenity-book#35]
> serenity.version and serenity.maven.version should always be identical

why even have 2 properties then?

@wakaleo any reason I shouldn't update the docs to reflect that?

**Comment by wakaleo** [comment]
Sometimes for testing it is useful to have two. In theory they have different release cycles.

**Comment by globalworming** [comment]
so... for framework development you mean?
usually not for consumers?

**Comment by wakaleo** [comment]
Yep, for consumers it should be the same.
