### ISSUE TITLE
Please fix the online book, doesn't show correctly.

### ISSUE THREAD

**Issue by ldy810** [serenity-bdd/the-serenity-book#40]
Open : https://serenity-bdd.github.io/theserenitybook/latest/index.html, Show as below image.
![image](https://user-images.githubusercontent.com/6262632/82627280-a33e2e00-9c1c-11ea-9069-f294137e3580.png)

**Comment by globalworming** [comment]
There were layout changes, maybe @wakaleo somehow didn't deploy all resources.. Looks fine locally

**Comment by ldy810** [comment]
Yes, the link of chapter is not available.

**Comment by globalworming** [comment]
Should be fine now
